### ISSUE TITLE
markdown-mode installation failed on cl-lib dependency for EMACS 25.1.1 or 22.1.1

### ISSUE THREAD

**Issue by zoeeer** [dunn/homebrew-emacs#579]
When installing markdown-mode, I encountered the same problem to #205 , ie. compilation failed due to "Cannot open load file: cl-lib". Manually installing cl-lib does not resolve this.

I'm on OSX, and I have pre-installed GNU Emacs 22.1.1, as well as a desktop version GNU Emacs 25.1.1.

cl-lib installed successfully:
```
$ brew info cl-lib
homebrew/emacs/cl-lib: stable 0.6.1 (bottled)
Compatibility library for Emacs 24's cl-lib
https://elpa.gnu.org/packages/cl-lib.html
/usr/local/Cellar/cl-lib/0.6.1 (4 files, 20.7KB) *
  Poured from bottle on 2017-03-17 at 14:54:36
From: https://github.com/Homebrew/homebrew-emacs/blob/master/Formula/cl-lib.rb
==> Requirements
Required: emacs ✔
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cl-lib
```

markdown-mode failed:
```
==> Installing markdown-mode from homebrew/emacs
==> Downloading https://github.com/jrblevin/markdown-mode/archive/v2.1.tar.gz
Already downloaded: /Users/rang/Library/Caches/Homebrew/markdown-mode-2.1.tar.gz
==> Byte compiling markdown-mode.el

In toplevel form:
markdown-mode.el:864:1:Error: Cannot open load file: cl-lib

Error: Byte compilation failed
emacs --batch -Q --directory /private/tmp/markdown-mode-20170318-99073-l8fvgl/markdown-mode-2.1 --directory /private/tmp/markdown-mode-20170318-99073-l8fvgl/markdown-mode-2.1/scripts --directory /private/tmp/markdown-mode-20170318-99073-l8fvgl/markdown-mode-2.1/tests -f batch-byte-compile markdown-mode.el
```

**Comment by zoeeer** [comment]
@dunn Here's the issue and thanks.

**Comment by dunn** [comment]
What does `emacs --version` say?  How did you install Emacs?/

**Comment by zoeeer** [comment]
I have two installations:
Emacs 22.1.1 is pre-installed on my OSX, while
Emacs 25.1.1 is the desktop version I downloaded from https://emacsformacosx.com/

```
$ emacs --version
GNU Emacs 22.1.1
Copyright (C) 2007 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

```
$ /Applications/Emacs.app/Contents/MacOS/Emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

I ususally use the GUI version.

**Comment by dunn** [comment]
Gotcha, thanks.  

Markdown mode requires at least version 24.4 of Emacs (https://github.com/dunn/homebrew-emacs/blob/master/Formula/markdown-mode.rb#L16), so if it's the 22.1 version that is used when you run `emacs` on the command-line, Homebrew should notice and install a newer version of Emacs.  But for some reason it's not.

The easiest fix would be to add `/Applications/Emacs.app/Contents/MacOS/Emacs` to your `$PATH` environment variable in front of the old 22.1 version; then it should always be used by default, even by Homebrew.

**Comment by zoeeer** [comment]
@dunn Done. Thanks!

**Comment by dunn** [comment]
No problem! Everything working now?

**Comment by Cumol** [comment]
Moving `/usr/local/bin` before `/usr/bin` solved the issue for me.
