### ISSUE TITLE
Odd error displayed when updating Homebrew

### ISSUE THREAD

**Issue by Alhadis** [dunn/homebrew-emacs#603]
Whenever the `homebrew-emacs` tap is updated, the following error is emitted:
~~~
Updated Homebrew from f3dc06a4e to cfe2c3c90.
Updated 2 taps (dunn/emacs, homebrew/science).
==> Updated Formulae
dunn/emacs/company-mode
Error: dash-emacs from dunn/emacs is given, but old name dash was installed from homebrew/core.

Please try to use dash to refer the formula.
To force migrate use `brew migrate --force dash`.
~~~

I have no idea how to get rid of it, because the force-migrate tip doesn't help:
~~~
λ Desktop: brew migrate --force dash
Error: dash doesn't replace any formula.
~~~

I have the [`dash`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dash.rb) formula installed, but reinstalling it does nothing to banish this odd little nag.

**Comment by dunn** [comment]
Ack, sorry about that.  The repository itself was moved from the Homebrew organization back to my namespace, so `brew` got a little confused.  I think in this case there's also the fact that `dash` got renamed to `dash-emacs` since you last updated.  Probably the easiest thing is to uninstall and reinstall, and `brew untap homebrew/emacs` for good measure.

Let me know if that works, and sorry again for the inconvenience!

**Comment by Alhadis** [comment]
@dunn Do you mean uninstall and reinstall all of Homebrew? :|

Uhm, I'd rather not. Isn't there a simpler way, like hacking the crap out of a JSON file somewhere?

**Comment by dunn** [comment]
Oh no, just dash: `brew remove --force dash && brew install dash-emacs`.

**Comment by Alhadis** [comment]
Nope, no such luck. :(

**Comment by dunn** [comment]
What's the output?

Were you able to `brew untap homebrew/emacs`?

**Comment by Alhadis** [comment]
Nope:

~~~
λ brew untap homebrew/emacs
Error: No available tap homebrew/emacs.
~~~

**Comment by dunn** [comment]
Huh, that is weird.  Maybe try manually deleting the old dash with `rm -rf $(brew --cellar)/dash`?

**Comment by Alhadis** [comment]
I'd be looking at patching Homebrew somewhere...

**Comment by dunn** [comment]
If that didn't work, I'm afraid I'm out of ideas.

**Comment by Alhadis** [comment]
:(

**Comment by Alhadis** [comment]
For the sake of posterity and a happy ending, I thought I'd let you know that running `brew migrate --force dash` again recently fixed the issue for me. :D

However, I *did* need to manually delete a symlink in `/usr/local/Cellar`, which was causing `brew reinstall dash` to reinstall `dash-emacs` instead. Looking in that directory showed `/usr/local/Cellar/dash` was aliasing `/usr/local/Cellar/dash-emacs`. Once removed, I could install `dash` normally, and they both co-exist happily ever after. 😄

~~~console
$ Cellar: ls -alh /usr/local/Cellar | grep dash
drwxr-xr-x    3 johngardner  admin   102B 24 Sep 09:15 dash
drwxr-xr-x    3 johngardner  admin   102B 24 Sep 09:13 dash-emacs
~~~

**Comment by dunn** [comment]
Yay, I'm glad you managed to resolve it!
