### ISSUE TITLE
pdf-tools: poppler 0.59.0_1 compatibility issue

### ISSUE THREAD

**Issue by kaz-yos** [dunn/homebrew-emacs#694]
With the latest poppler (version 0.59.0_1), the following compatibility issue was experienced. Downgrading poppler by ```$ brew switch poppler 0.57.0_1``` solved the issue for now. I'm investigating if there is a better way to fix this.

```
$ brew install pdf-tools
Updating Homebrew...
==> Installing pdf-tools from dunn/emacs
==> Downloading https://github.com/politza/pdf-tools/archive/v0.70.tar.gz
Already downloaded: /Users/kazuki/Library/Caches/Homebrew/pdf-tools-0.70.tar.gz
==> make server/epdfinfo
Last 15 lines from /Users/kazuki/Library/Logs/Homebrew/pdf-tools/01.make:
configure.ac:11: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
cd server && ./configure -q
configure: WARNING: Annot.h: present but cannot be compiled
configure: WARNING: Annot.h:     check for missing prerequisite headers?
configure: WARNING: Annot.h: see the Autoconf documentation
configure: WARNING: Annot.h:     section "Present But Cannot Be Compiled"
configure: WARNING: Annot.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------- ##
configure: WARNING:     ## Report this to politza@fh-trier.de ##
configure: WARNING:     ## ---------------------------------- ##
configure: error: cannot find necessary  poppler-private header (see README.org)
make: *** [server/Makefile] Error 1
```

**Comment by cerkut** [comment]
Same problem here, and thanks for the workaround.

**Comment by malcolmpurvis** [comment]
I can pdf-tools from source with the latest version of poppler if I add '-std=c++11' to CXXFLAGS.

I haven't worked out how to do that in the brew formula.

**Comment by dunn** [comment]
@malcolmpurvis looks like you got it right: https://github.com/politza/pdf-tools/issues/306

Backport incoming: https://github.com/dunn/homebrew-emacs/pull/696 (and you can also always `brew install --HEAD pdf-tools` which contains the fix).

**Comment by kaz-yos** [comment]
@dunn, Thank you so much!

**Comment by dunn** [comment]
Oh I somehow missed that 0.80 was released, which includes that commit.  I'll just update the formula instead of doing a backport.
