### ISSUE TITLE
Warning: Calling Requirement.default_formula is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by yetisyny** [dunn/homebrew-emacs#724]
So, remember #721, that issue about the error message “Warning: Calling 'depends_on :emacs' is deprecated!” That one was closed earlier today, January 23, 2018, good job with that by the way.

Well there is a similar issue now but it is just a little bit different. Now for 2 of the .rb files, one a formula, one under Homebrew/requirements, both here in this tap, I get a similar error. Here is the error message:

`Warning: Calling Requirement.default_formula is deprecated!`
`There is no replacement.`
``/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/Homebrew/requirements/emacs_requirement.rb:3:in `<class:EmacsRequirement>'``
`Please report this to the homebrew/emacs tap!`

`Warning: Calling Requirement.default_formula is deprecated!`
`There is no replacement.`
``/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/Formula/slime.rb:5:in `<class:CommonLispRequirement>'``
`Please report this to the homebrew/emacs tap!`

You can get this error message by running the command “brew which-update” if you have the [homebrew/command-not-found](https://github.com/Homebrew/homebrew-command-not-found) repository tapped along with homebrew/emacs.

Or you can get it by running the command “brew search homebrew/emacs” with homebrew/emacs tapped.

Or if you type in “brew info slime” when homebrew/emacs is tapped, you get the same error.

I am guessing that this probably breaks things because in the previous issue, #721, this type of error broke things.

It looks like you may be aware of the issue with emacs_requirement.rb but I think I am the first to report the issue with slime.rb involving the common lisp requirement. Anyway the error message told me to report the issue here so I did what it said.

I have no idea how you are supposed to fix this, unfortunately. Good luck, sorry about not having a solution! Hopefully you can duplicate this error message and figure out what is causing it and fix it.

**Comment by dunn** [comment]
I'm going to try the easy fix of just removing the `default_formula` line; I think that will just mean when the user doesn't have any Emacs installed, they'll have to manually `brew install emacs` instead of having it done for them: https://github.com/dunn/homebrew-emacs/pull/725

**Comment by weallcock** [comment]
You may not have deployed the fix yet, but I just did a brew update and got the same thing:

$ brew update
Warning: Calling Requirement.default_formula is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/Homebrew/requirements/emacs_requirement.rb:3:in `<class:EmacsRequirement>'
Please report this to the homebrew/emacs tap!

**Comment by dunn** [comment]
Just merged, let me know if it works!

**Comment by weallcock** [comment]
Yes indeed, a clean update.
