### ISSUE TITLE
issue installing pdf-tools

### ISSUE THREAD

**Issue by csmithchicago** [dunn/homebrew-emacs#743]
Trying to install pdf-tool, I am getting the following error about types.

$ brew install pdf-tools.rb 
==> Installing pdf-tools from dunn/emacs
==> Downloading https://github.com/politza/pdf-tools/archive/v0.80.tar.gz
Already downloaded: /Users/CSmith/Library/Caches/Homebrew/pdf-tools-0.80.tar.gz
==> make server/epdfinfo
Last 15 lines from /Users/CSmith/Library/Logs/Homebrew/pdf-tools/01.make:
clang -DHAVE_CONFIG_H -I.    -w  -g -O2 -MT libsynctex_a-synctex_parser_utils.o -MD -MP -MF .deps/libsynctex_a-synctex_parser_utils.Tpo -c -o libsynctex_a-synctex_parser_utils.o `test -f 'synctex_parser_utils.c' || echo './'`synctex_parser_utils.c
mv -f .deps/libsynctex_a-synctex_parser_utils.Tpo .deps/libsynctex_a-synctex_parser_utils.Po
poppler-hack.cc:88:16: error: cannot initialize a variable of type 'GooString *' with an rvalue of type 'const GooString *'
    GooString *state = a->annot->getAppearState ();
               ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
poppler-hack.cc:108:19: error: assigning to 'GooString *' from incompatible type 'const GooString *'
    text = annot->getDate ();
           ~~~~~~~^~~~~~~~~~
2 errors generated.
make[2]: *** [epdfinfo-poppler-hack.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libsynctex_a-synctex_parser.Tpo .deps/libsynctex_a-synctex_parser.Po
mv -f .deps/epdfinfo-epdfinfo.Tpo .deps/epdfinfo-epdfinfo.Po
make[1]: *** [all] Error 2
make: *** [server/epdfinfo] Error 2

**Comment by dunn** [comment]
Looks like it might be this issue: https://github.com/politza/pdf-tools/issues/372

I wonder if we're building against a new version of poppler with some breaking change.

**Comment by bhanuvrat** [comment]
This error was resolved by https://github.com/politza/pdf-tools/pull/373#event-1587917627
but homebrew is still trying to build v0.80 and failing.

**Comment by csmithchicago** [comment]
ok, thank you for the update

**Comment by dunn** [comment]
I asked them to tag a new release; in the meantime you can `brew install pdf-tools --HEAD`.
